version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.credentials:/root/.credentials
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --reload 